### ISSUE TITLE
New data not visible when intersection is triggered

### ISSUE THREAD

**Issue by yngfoxx** [ElSierra/search-test#1]
## Weldone!

- The application of the `useReducer` hook is spot on.
- The `useEffect` clean up was also a good one!
- Intersection Observer was also a clever way to detect screen position against scroll view.

## Minor issues spotted

The bug
![image](https://github.com/ElSierra/search-test/assets/47150226/fb02353f-84d0-43f9-a640-818a6ba1d08d)

The logs
![image](https://github.com/ElSierra/search-test/assets/47150226/c978b3d5-81f2-4e71-a236-2935daf9aee1)

**Comment by ElSierra** [comment]
fixed
